### ISSUE TITLE
Delete motion sensors / Setup code issues with Hombridge UI v4.52.0

### ISSUE THREAD

**Issue by mensa84** [maxileith/homebridge-appletv-enhanced#10]
Hello,

is it possible to delete the motion sensors?
I would prefer to just be able to turn on and off the Apple TV and see the current power state. Is this possible?

**Comment by maxileith** [comment]
Hi @mensa84 ,

yes this is possible. You just need to unselect media types and device stats in the Config UI for this plugin.

Note that there was a bug regarding unselecting all motion sensors in the config that may be problematic for your usecase: #9. However, this is fixed in Version v0.3.0-beta.3

**Comment by mensa84** [comment]
I have already v0.3.0-beta.3 and this is my config. But I still get every motion sensor:

`        {
            "mediaTypes": [],
            "deviceStates": [],
            "remoteKeysAsSwitch": [],
            "blacklist": [],
            "name": "Apple TV Enhanced",
            "platform": "AppleTVEnhanced"
        }`

**Comment by mensa84** [comment]
I removed 1 Apple TV from Home App now and tried to add it again, but Homebridge Crashes with that errors:

```
[11/4/2023, 5:27:26 PM] Error: Unable to execute request 15: Traceback (most recent call last):File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
    await futasyncio.exceptions.CancelledErrorThe above exception was the direct cause of the following exception:Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 163, in _send_command
    resp = await self._protocol.exchange_opack(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 154, in exchange_opack
    return await self._exchange_generic_opack(frame_type, data, identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 167, in _exchange_generic_opack
    unpacked_object = await self._queues[identifier].wait(timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/collections.py", line 160, in wait
    await asyncio.wait_for(self._event.wait(), timeout)File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from excTimeoutErrorThe above exception was the direct cause of the following exception:Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/__init__.py", line 571, in _connect
    await api.connect()File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 145, in connect
    await self.system_info()File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 184, in system_info
    await self._send_command(File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 174, in _send_command
    raise exceptions.ProtocolError(f"Command {identifier} failed") from expyatv.exceptions.ProtocolError: Command _systemInfo failed>>> An error occurred, full stack trace above
    at /usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at a (/usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/4/2023, 5:27:26 PM] Error: Unable to execute request D: Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 163, in _send_command
    resp = await self._protocol.exchange_opack(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 154, in exchange_opack
    return await self._exchange_generic_opack(frame_type, data, identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 167, in _exchange_generic_opack
    unpacked_object = await self._queues[identifier].wait(timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/collections.py", line 160, in wait
    await asyncio.wait_for(self._event.wait(), timeout)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/__init__.py", line 571, in _connect
    await api.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 145, in connect
    await self.system_info()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 184, in system_info
    await self._send_command(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 174, in _send_command
    raise exceptions.ProtocolError(f"Command {identifier} failed") from ex
pyatv.exceptions.ProtocolError: Command _systemInfo failed

>>> An error occurred, full stack trace above
    at /usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at a (/usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by maxileith** [comment]
> I have already v0.3.0-beta.3 and this is my config. But I still get every motion sensor

Can you check again with v0.3.0-beta.4 ?

**Comment by maxileith** [comment]
> I removed 1 Apple TV from Home App now and tried to add it again, but Homebridge Crashes with that errors:

Have you changed your access settings of you Speakers and TVs in your Home? It has to be set to everyone or anyone who is in the same network.

**Comment by mensa84** [comment]
> > I removed 1 Apple TV from Home App now and tried to add it again, but Homebridge Crashes with that errors:
> 
> Have you changed your access settings of you Speakers and TVs in your Home? It has to be set to everyone or anyone who is in the same network. See #5

It is set to "Everyone".

**Comment by mensa84** [comment]
I have another problem now. I did blacklist 2 Apple TVs in config:

```
        {
            "mediaTypes": [],
            "deviceStates": [],
            "remoteKeysAsSwitch": [],
            "blacklist": [
                "f0:b3:ec:0e:bd:6a",
                "ec:a9:07:18:1d:2e"
            ],
            "name": "Apple TV Enhanced",
            "platform": "AppleTVEnhanced"
        }
```

But the plugin still tries to connect:

```
[11/4/2023, 5:57:47 PM] [Apple TV Enhanced] Schlafzimmer Apple TV (F0:B3:EC:16:65:03): Pairing request timed out, retrying ...
[11/4/2023, 5:57:47 PM] [Apple TV Enhanced] Studio Apple TV (EC:A9:07:05:D6:98): Pairing request timed out, retrying ...
```

**Comment by maxileith** [comment]
This is a known issue that I should document in the README. Basically Apple TVs report another MAC-Address when scanning for Airplay devices. This is why the logged MAC-Adresses don't match with the MAC-Addresses in the settings of your Apple TVs. Just use the MAC-Adresses from the log for the blacklist instead.

**Comment by mensa84** [comment]
> > I have already v0.3.0-beta.3 and this is my config. But I still get every motion sensor
> 
> Can you check again with v0.3.0-beta.4 ?

Now it says (when adding in Home app), that the configuration code is wrong!?
Before it worked with old Homebridge code 03145154. I see that new Homebridge version uses now 58310422, but also does not work.
Where may I find the code for pairing?

**Comment by mensa84** [comment]
Logfile says: `[11/4/2023, 6:04:42 PM] Please add [Apple TV Wohnzimmer Apple TV 2E32] manually in Home app. Setup Code: 5831-0422`

Screenshots:
![Screenshot000125](https://github.com/maxileith/homebridge-appletv-enhanced/assets/30125802/8a14d6b4-34cf-46ef-8759-2fe1a2575fbd)
![Screenshot000126](https://github.com/maxileith/homebridge-appletv-enhanced/assets/30125802/90667d17-c0fb-4a6a-8d41-763e24068e12)

**Comment by maxileith** [comment]
> I removed 1 Apple TV from Home App now and tried to add it again, but Homebridge Crashes with that errors:

Is this issue somehow reproducible? A step by step guide to get this error would be good for me in order to reproduce the error and understand what is happening.

**Comment by maxileith** [comment]
Regarding the wrong setup code I do not have a clue. This handles by homebridge in the background, the plugin has nothing to do with this. Did you maybe update to homebridge 1.7.0?

**Comment by mensa84** [comment]
Yes, I did update to 1.7.0 and I am trying the correct code, which is also shown in the logfiles.

**Comment by maxileith** [comment]
So usually the code to setup the Apple TV is the same as the one displayed on your dashboard of homebridge. Maybe restart everything then test again. As I said, I do not have any influence on the setup code from the plugin side.

**Comment by mensa84** [comment]
I tried this all, but nothing helped :(

**Comment by maxileith** [comment]
Have you downgraded to homebridge v1.6.1 and tried again?

**Comment by mensa84** [comment]
Yes, I restored a snapshot now and do have the same problem. I think the problem of update Homebridge UI v4.52.0
Since that version the code is generated dynamically and seems not to work.

**Comment by maxileith** [comment]
> Yes, I restored a snapshot now and do have the same problem. I think the problem of update Homebridge UI v4.52.0
> 
> Since that version the code is generated dynamically and seems not to work.

So you have downgraded the Homebridge UI v4.51.2 and now it is working again?

**Comment by mensa84** [comment]
Yes, with Homebridge UI v4.51.2 and Homebridge v1.7.0 it is no problem to add the device. Code is working, thank you!
With your release v0.3.0-beta.4 it is now also working to have 0 motion sensors :)

Do you know, if that input sources can be changed later? Or is the only way to change it to delete and re-add that Apple TV?
![Screenshot000127](https://github.com/maxileith/homebridge-appletv-enhanced/assets/30125802/74b26126-e86a-4d6d-b324-6d9914967244)

**Comment by maxileith** [comment]
Okay, good news! Do you have any open questions or can we close this?

**Comment by mensa84** [comment]
That's it, thank you for your fast help!
